# Generated by Django 5.1.2 on 2025-03-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_part', models.CharField(max_length=50, verbose_name='Название детали')),
                ('description_part', models.CharField(max_length=250, verbose_name='Описание детали')),
                ('cost_part', models.IntegerField(verbose_name='Цена')),
                ('presence_part', models.BooleanField(verbose_name='Есть ли в наличии?')),
                ('link_picture', models.TextField(verbose_name='Ссылка на картинку')),
            ],
        ),
    ]
