# Generated by Django 5.1.2 on 2025-03-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='details',
            options={'verbose_name': 'Деталь', 'verbose_name_plural': 'Детали'},
        ),
    ]
