# Generated by Django 5.1.2 on 2025-03-03 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_details_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='link_picture',
            field=models.TextField(default='', verbose_name='Ссылка на картинку'),
        ),
    ]
